### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by odelmalv** [dudeofawesome/unrailed-save-scummer#1]
Hello dudeofawesome
First of all thank you for developing this program, its a cool feature to have when you want to save some time and try higher difficulties. I tried to use the tool in the current version of Unrailed but it did not worked. Could you provide me some assistance please? Thank you
I ran the executable before starting the game. I loaded my saved game, played, crashed and then I looked for some backup folder or somethig and I didnt find any. Thank you for your time. Peace

**Comment by dudeofawesome** [comment]
Were you saving your game at each railway station? Unfortunately, the game only creates save-states when you manually save, so I'm only able to create backups from manual saves.

**Comment by odelmalv** [comment]
No, I was not saving at each station. I was playing endless mode in extreme.

**Comment by odelmalv** [comment]
@dudeofawesome I just created and new game in endless-extreme, passed the first station, manually saved the game, loaded the game, and crashed. I started another game again, and this time I was able to load the manual save! :D I guess I was doing it wrong. Thanks for your answer :) ! <3
